### ISSUE TITLE
summarizeNHTS

### ISSUE THREAD

**Issue by dnimish85** [Westat-Transportation/summarizeNHTS#2]
I can't load the summarizeNHTS.

I was trying  " devtools::install_github('Westat-Transportation/summarizeNHTS') " but got following error:  Is it related to data download or something else ? 

Downloading GitHub repo Westat-Transportation/summarizeNHTS@master
from URL https://api.github.com/repos/Westat-Transportation/summarizeNHTS/zipball/master
Installing summarizeNHTS
"C:/PROGRA~1/R/R-34~1.3/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/ndharmadhikari/AppData/Local/Temp/RtmpMFK3Q3/devtools2d80322f2463/Westat-Transportation-summarizeNHTS-7bccbaf"  \
  --library="\\server-file/users/ndharmadhikari/R/win-library/3.4" --install-tests 

* installing *source* package 'summarizeNHTS' ...
** libs

*** arch - i386
C:/RBuildTools/3.4/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-34~1.3/include" -DNDEBUG  -I"\\server-file/users/ndharmadhikari/R/win-library/3.4/Rcpp/include"        -O2 -Wall  -mtune=generic -c RcppExports.cpp -o RcppExports.o
RcppExports.cpp:4:18: fatal error: Rcpp.h: No such file or directory
 #include <Rcpp.h>
                  ^
compilation terminated.
make: *** [RcppExports.o] Error 1
Warning: running command 'make -f "C:/PROGRA~1/R/R-34~1.3/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-34~1.3/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="summarizeNHTS.dll" OBJECTS="RcppExports.o cpp_helper_functions.o"' had status 2
ERROR: compilation failed for package 'summarizeNHTS'
* removing '\\server-file/users/ndharmadhikari/R/win-library/3.4/summarizeNHTS'
In R CMD INSTALL
Installation failed: Command failed (1)

**Comment by afcates** [comment]
Looks like a compilation problem. Have you installed [Rtools](https://cran.r-project.org/bin/windows/Rtools/)? If not, install it and then try the package install again.

**Comment by dnimish85** [comment]
I have Rtools installed, but still got same error.

**Comment by afcates** [comment]
Ok, can you try installing Rcpp on its own first?
 `install.packages('Rcpp')`

**Comment by dnimish85** [comment]
Sorry, it's same result. I guess I am missing something.

**Comment by dnimish85** [comment]
I tried to install this on my laptop and it worked. 

Our IT person thinks it needs to install package on the C drive. This is trying to install it on the server drive / user drive. Do you know if there is a way to force it to install it on C drive ?

**Comment by dnimish85** [comment]
I figured it out. 

1) I uninstalled everything (R, Rtools, Rstudio) 
2) Deleted whatever R files / folders in my server drive
3) Installed everything again
4) While installing forced them to save in the C:\Users\(UserNAME) Directory
5) Checked again if everything is going in the server drive
6) SummerzieNHTS is loaded now.
