### ISSUE TITLE
Missing variables in 2017 data

### ISSUE THREAD

**Issue by m-mcnamara** [Westat-Transportation/summarizeNHTS#4]
Hello,
I've been using the library to do some analysis on the 2017 data and it is working great aside from a few missing variables. I am particularly interested in the questions related to why respondents don't bike or walk more.

Here is a list of variables that appear in the data dictionary and csvs, but not the data imported using read_data (not counting ID and weight columns):

ALT_16 | Alternative Mode of   Transportation: Public Transportation or Taxi
ALT_23 | Alternative Mode of Transportation: Passenger to Friend/Family Member or Rental Car
ALT_45 | Alternative Mode of Transportation: Bicycle or Walk
BIKE_DFR | Reason for Not Biking More: Infrastructure
BIKE_GKP | Reason for Not Biking More: Safety
SMPLSRCE | Sample where the case originated
TDCASEID | Unique identifier for every trip record in the file
TDTRPNUM | Incrementing travel day trip number, starting at 1 for each person in the file
TRACC_BUS | Bus as mode used to get to public transit?
TRACC_CRL | Rail as mode used to get to public transit?
TRACC_OTH | Other mode used to get to public transit?
TRACC_POV | POV as mode used to get to public transit?
TRACC_SUB | Subway as mode used to get to public transit?
TRACC_WLK | Walk as mode used to get to public transit?
TREGR_BUS | Bus as mode used to get from public transit?
TREGR_CRL | Rail as mode used to get from public transit?
TREGR_OTH | Other mode used to get from public transit?
TREGR_POV | POV as mode used to get from public transit?
TREGR_SUB | Subway as mode used to get from public transit?
TREGR_WLK | Walk as mode used to get from public transit?
WALK_DEF | Reason for Not Walking More: Infrastructure
WALK_GKQ | Reason for Not Walking More: Safety

If it's an error on my end, I'm happy to provide more code or information.

Thanks!

Maggie

**Comment by AnthonyFucci** [comment]
Maggie, thanks for pointing this issue out. It looks like the package's internal codebook has a few holes, and that is restricting these variables from getting read in. It also means we don't have the labels for these answers baked in either. I'm going to elevate this issue but in the meantime you can get by using the following code as an example:

```R
library(summarizeNHTS)
new_variables <- rbind(
	data.table::data.table(NAME = "BIKE_GKP", TABLE = "person", TYPE = "character", LABEL = "Reason for Not Biking More: Safety"),
	data.table::data.table(NAME = "SMPLSRCE", TABLE = "household", TYPE = "character", LABEL = "Sample where the case originated")
	#, etc, etc
)
codebook_2017$variables <- rbind(codebook_2017$variables, new_variables)
nhts_data <- read_data("2017", "C:/NHTS")
# using the variables should work now:
summarize_data(data = nhts_data, agg = "person_count", by = "BIKE_GKP")
```

We will resolve the issue for good by diffing the latest public files with the package's internal codebook and inserting the missing records.

**Comment by m-mcnamara** [comment]
Thanks for the workaround, Anthony!

**Comment by afcates** [comment]
The variables (and associated value code labels) listed above have been added to the package's internal 2017 codebook. The example listed above will now work without having to manipulate the codebook_2017 object.
