### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by murraywisdot** [Westat-Transportation/summarizeNHTS#5]
Install Error with 3.4.3 and stringi - 

> library(summarizeNHTS)
Loading required package: ggplot2
Error: package or namespace load failed for ‘summarizeNHTS’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘stringi’
In addition: Warning message:
package ‘ggplot2’ was built under R version 3.4.4 

> install.packages("summarizeNHTS")
Installing package into ‘C:/Users/DOTJEM/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘summarizeNHTS’ is not available (for R version 3.4.3)

**Comment by AnthonyFucci** [comment]
Thanks for filing this. Can you post the results of the following from a new RStudio R session:
```r
remove.packages("stringi")
library(summarizeNHTS) # this should continue to fail
install.packages("stringi") # select no (y/n) to any prompt asking about compilation
library(summarizeNHTS) # this should work now
```

If you still get an error, can you run the following and post?
```r
packageVersion("stringi")
sessionInfo()
```

**Comment by murraywisdot** [comment]
From the new RStudio R Session - Here's the results from the first:
***
> remove.packages("stringi")
Removing package from ‘C:/Users/DOTJEM/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
Error in remove.packages : there is no package called ‘stringi’
> library(summarizeNHTS) # this should continue to fail
Loading required package: ggplot2
Error: package or namespace load failed for ‘summarizeNHTS’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘stringi’
In addition: Warning message:
package ‘ggplot2’ was built under R version 3.4.4 
> install.packages("stringi") # select no (y/n) to any prompt asking about compilation
Installing package into ‘C:/Users/DOTJEM/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)

  There is a binary version available but the source version is later:
        binary source needs_compilation
stringi  1.1.7  1.2.3              TRUE

Do you want to install from sources the package which needs compilation?
y/n: library(summarizeNHTS) # this should work now
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/stringi_1.1.7.zip'
Content type 'application/zip' length 14295248 bytes (13.6 MB)
downloaded 13.6 MB

package ‘stringi’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\DOTJEM\AppData\Local\Temp\RtmpyO6kHC\downloaded_packages

**Comment by murraywisdot** [comment]
I think it's working
