### ISSUE TITLE
Incorrect variable labels in 2017 codebook

### ISSUE THREAD

**Issue by sbrumb** [Westat-Transportation/summarizeNHTS#8]
In the package's internal codebook for the 2017 NHTS, the variable labels for the "medical condition results in..." variables (CONDNIGH, CONDPUB, CONDRIVE, CONDRIDE, CONDSPEC, CONDTAX, CONDTRAV) appear to be incorrect. When I use summarize_data(), they all return labels with "Reduced [$YOUR2] day-to-day travel" (for code "01") or "Asked others for rides" (for code "02"). As a result, in the case of CONDRIDE, "asked others for rides" appears to have the opposite meaning.

EDIT: I'm using the latest version of summarizeNHTS (0.0.0.9000).

Code to reproduce the issue:

```
library(summarizeNHTS)

download_nhts_data("2017")
nhts2017 <- read_data("2017")

summarize_data(
  data = nhts2017,
  agg = "person_count",
  by = c("CONDNIGH")
)

summarize_data(
  data = nhts2017,
  agg = "person_count",
  by = c("CONDPUB")
)

summarize_data(
  data = nhts2017,
  agg = "person_count",
  by = c("CONDRIDE")
)

summarize_data(
  data = nhts2017,
  agg = "person_count",
  by = c("CONDRIVE")
)

summarize_data(
  data = nhts2017,
  agg = "person_count",
  by = c("CONDSPEC")
)

summarize_data(
  data = nhts2017,
  agg = "person_count",
  by = c("CONDTAX")
)

summarize_data(
  data = nhts2017,
  agg = "person_count",
  by = c("CONDTRAV")
)

```

**Comment by AnthonyFucci** [comment]
Thanks for reporting this! I'm not sure how long these variable label discrepancies with the public file have existed. I looked for more but these 7 are all I found. Update the package for the correct labels.
```r
devtools::install_github('Westat-Transportation/summarizeNHTS')
```

**Comment by sbrumb** [comment]
Sorry for the delay -- just updated the package and verified that the 7 "medical condition results in..." variables return the expected labels and percentages. Thank you for fixing this!

**Comment by marcelo-g-simas** [comment]
Closing.
